server:
  # Mod_admin模块端口号就要8081不要改！
  port: 8081
# Mod_admin模块服务名配置
service:
  setting: Mod_admin

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music_dreamer?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: zwz050418
  application:
    # 服务名就要Mod_admin不要改！
    name: Mod_admin
  # 暂时禁用Nacos服务发现
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: localhost:8848
    # 禁用Spring Cloud兼容性检查
    compatibility-verifier:
      enabled: false
  #连接redis数据库6379端口不要改！
  data:
    redis:
      port: 6379
      host: localhost

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 启用驼峰命名转换
  mapper-locations: classpath*:mapper/*.xml  # Mapper XML文件路径

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'